#!/bin/bash

video=$(xclip -o)
declare -A myArray=( [720]=1 [Best]=2 )
choice=$(printf "%s\n" "${!myArray[@]}" | dmenu -fn monospace-14)

if [ "${myArray[$choice]}" == "1" ]
then
	notify-send 'Загрузка 720 стартовала!' &
	yt-dlp -f 'bv[height=720][ext=mp4]+ba[ext=m4a]' $video -o '/home/q/Videos/%(title)s.%(ext)s'
	notify-send 'Загрузка завершена!'
else
	notify-send 'Загрузка BEST стартовала!'
	yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' $video -o '/home/nolonday/VideosYT/%(title)s.%(ext)s'
	notify-send 'Загрузка завершена!'
fi
