#!/bin/env bash

choice=$(printf "Lock\nLogout\nReboot\nShutdown" | rofi -dmenu)
case "$choice" in
  Lock) betterlockscreen -l ;;
  Logout) pkill -KILL -u "$USER" ;;
  Reboot) reboot ;;
  Shutdown) poweroff ;;
esac
