#!/bin/bash

# Set a random wallpaper from the specified folder
feh --randomize --bg-fill ~/wallpapers/*
# Get the current wallpaper from .fehbg
wallpaper="$(cat "${HOME}/.fehbg" | awk -F "'" '{print $2}')"
# Apply pywal color scheme to desktop
wal -i $wallpaper
pywalfox update 
wal-telegram --wal
wpg image
betterlockscreen -u $wallpaper
